### PR TITLE
docs: add rules

### PR DESCRIPTION
**Pull request by KY64**
This pull request fixes issue #1

I've added documentation for rules that applied to this configuration so it would help developers to understand the rules in this configuration.

### CODE REVIEW

**Comment by KY64** [comment]
Do you think it's ready to be merged or is there any further change needed?

**Comment by grikomsn** [comment]
See [`eslint-plugin-react`'s approach on documenting rules](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules). We should separate main readme and rule readme by add a `rules.md` so it's grouped in it's own page.

cc @KY64

**Comment by KY64** [comment]
Oh, right. I'll try to reorganize it then

**Comment by KY64** [comment]
I've done organizing the rule documentation into dedicated files inside **docs/rules** directory. The folder structure has changed into:

```
├── LICENSE
├── README.md
├── docs
│   └── rules
│       ├── import-extensions.md
│       ├── newline-after-import.md
│       ├── no-explicit-any.md
│       ├── no-unsafe-assignment.md
│       ├── restrict-template-expressions.md
│       ├── sort-export.md
│       └── sort-import.md
├── index.js
├── package.json
├── react.js
└── yarn.lock
```

I've also added a [table](https://github.com/KY64/eslint-config-kdnj/tree/docs/rules#rules) of overridden rules on this configuration by following the [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react#list-of-supported-rules) documentation as @grikomsn  suggested.

> P.S. Pardon me if it took a while to make this commit as I've got things to do.

**Review by grikomsn — APPROVED** [review]
LGTM!

**Pull request merged**
